version: "3"

services:
  database:
    image: postgres:latest
    volumes:
      - chat:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: chat
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "rkis"]
  cache:
    image: redis:latest
    ports:
      - "6379:6379"
  backend:
    build: .
    env_file:
      - .env
    ports:
      - 5000:5000
    depends_on:
      database:
        condition: service_healthy
volumes:
  chat:
